---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nanominer
data:
  config.ini: |-
    [VerusHash]
    wallet=RHRBxKG9FGzF2dcCjRXapUykCsyBZuGdQD
    paymentId = 0
    coin=Verus
    sortPools=true
    email=
    pool1=ap.luckpool.net:3956
